services:

  db:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      # Data persistence
      - ./data:/var/lib/postgresql/data
      # Schema setup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apinetwork

  api:
    container_name: apiserver
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - '80:8000'
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - apinetwork

volumes:
  db:
    driver: local

networks:
  apinetwork:
    driver: bridge
